language: java
deploy:
  provider: gae
  keyfile: client-secret.json
  project: good-punts
before_install:
- openssl aes-256-cbc -K $encrypted_cc220c246a36_key -iv $encrypted_cc220c246a36_iv
  -in client-secret.json.enc -out client-secret.json -d
